---
- name: Ensure Java is installed.
  apt: "name={{ item }} state=present"
  with_items: "{{ java_packages }}"

- name: Set Java Alternative
  command: update-java-alternatives --set java-1.8.0-openjdk-amd64
